# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev-polars-mp-bug-repro',
                'doc_host': 'https://daniel-vainsencher.github.io',
                'git_url': 'https://github.com/daniel-vainsencher/nbdev-polars-mp-bug-repro',
                'lib_path': 'nbdev_polars_mp_bug_repro'},
  'syms': { 'nbdev_polars_mp_bug_repro.core': { 'nbdev_polars_mp_bug_repro.core.foo': ( 'core.html#foo',
                                                                                        'nbdev_polars_mp_bug_repro/core.py')}}}